# Generated by Django 5.0.6 on 2024-05-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolioengine', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('realized_gain', models.FloatField()),
                ('unrealized_gain', models.FloatField()),
                ('total_gain', models.FloatField()),
                ('daily_profitability', models.FloatField()),
                ('accumulated_profitability', models.FloatField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('historicaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioengine.historicaldata')),
                ('quantity', models.FloatField()),
                ('average_cost', models.FloatField()),
            ],
            bases=('portfolioengine.historicaldata',),
        ),
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('positiondata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioengine.positiondata')),
                ('close', models.FloatField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.FloatField()),
            ],
            bases=('portfolioengine.positiondata',),
        ),
    ]
