# Generated by Django 5.0.6 on 2024-05-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioengine', '0003_historicaldata_positiondata_assetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('registration_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolioengine.country')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolioengine.allocationclass')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolioengine.asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolioengine.broker')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolioengine.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('brokerage_fee', models.FloatField()),
                ('other_fees', models.FloatField()),
                ('notes', models.CharField(max_length=200)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolioengine.position')),
            ],
        ),
    ]
