import { test, expect } from './auth-fixture'

test('create, price, edit and delete a position through the real API', async ({ page }) => {
  const errors: string[] = []
  let updates = 0
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', request => {
    if (request.method() === 'POST' && request.url().endsWith('/consolidate')) updates++
  })
  await page.goto('/')
  await page.getByRole('button', { name: '+ Carteira', exact: true }).click()
  await page.getByLabel('Nome da carteira', { exact: true }).fill('Browser test ' + Date.now())
  await page.getByRole('button', { name: 'Criar carteira', exact: true }).click()
  await page.getByRole('button', { name: '+ Nova transação', exact: true }).click()
  await page.getByRole('button', { name: 'Personalizado', exact: true }).click()
  await page.getByLabel('Instrumento', { exact: true }).fill('WEBTEST')
  await page.getByLabel('Nome do ativo', { exact: true }).fill('Web test asset')
  let finishCreation!: () => void
  const creationGate = new Promise<void>(resolve => { finishCreation = resolve })
  await page.route('**/api/instruments/custom', async route => {
    await creationGate
    await route.continue()
  })
  await page.getByRole('button', { name: 'Criar ativo personalizado', exact: true }).click()
  await page.getByLabel('Corretora', { exact: true }).fill('Teste')
  await page.getByLabel('Classe de alocação', { exact: true }).fill('Ações')
  await page.getByLabel('Data da negociação', { exact: true }).fill('2024-01-02')
  await page.getByLabel('Data da liquidação', { exact: true }).fill('2024-01-03')
  await page.getByLabel('Quantidade', { exact: true }).fill('10')
  await page.getByLabel('Preço unitário', { exact: true }).fill('20')
  await expect(page.getByRole('button', { name: 'Salvar transação', exact: true })).toBeDisabled()
  finishCreation()
  await expect(page.getByRole('button', { name: 'Trocar ativo', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Salvar transação', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('WEBTEST')
  await page.getByRole('button', { name: 'Cotações', exact: true }).click()
  await page.getByLabel('Fechamento', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Salvar cotação', exact: true }).click()
  await expect(page.getByRole('cell', { name: '30,0000' })).toBeVisible()
  await page.getByLabel('Data efetiva', { exact: true }).fill('2024-01-04')
  await page.getByLabel('Valor por unidade', { exact: true }).fill('12345.123456789012')
  let savedEventAmount: string | undefined
  await page.route('**/api/portfolios/*/assets/*/corporate-events', async route => {
    if (route.request().method() === 'POST') savedEventAmount = route.request().postDataJSON().amount_per_unit
    await route.continue()
  })
  await page.getByRole('button', { name: 'Adicionar evento', exact: true }).click()
  await expect(page.getByText(/Bruto 123\.451,2346 BRL/).first()).toBeVisible()
  expect(savedEventAmount).toBe('12345.123456789012')
  await expect(page.getByRole('heading', { name: 'Atividade do ativo' })).toBeVisible()
  await page.getByRole('button', { name: 'Posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('Custo BRL —')
  await expect(page.locator('tbody')).toContainText('atualização pendente')
  expect(updates).toBe(0)
  await page.getByRole('button', { name: 'Atualizar posições', exact: true }).click()
  // A manual quote does not certify missing corporate actions since the trade date.
  await expect(page.locator('tbody')).toContainText('Custo BRL 200,00')
  expect(updates).toBe(1)
  await expect(page.locator('tbody')).toContainText('valores incompletos')
  await page.screenshot({ path: 'test-results/positions-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Desempenho', exact: true }).click()
  await expect(page.getByText(/Histórico com dados incompletos/)).toBeVisible()
  await page.getByRole('button', { name: 'Transações', exact: true }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Quantidade', { exact: true }).fill('5')
  await page.getByRole('button', { name: 'Salvar transação', exact: true }).click()
  await page.getByRole('button', { name: 'Posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('Custo BRL 200,00')
  await expect(page.locator('tbody')).toContainText('atualização pendente')
  expect(updates).toBe(1)
  await page.getByRole('button', { name: 'Atualizar posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('Custo BRL 100,00')
  expect(updates).toBe(2)
  const selected = await page.getByLabel('Carteira', { exact: true }).inputValue()
  await page.reload()
  await page.getByLabel('Carteira', { exact: true }).selectOption(selected)
  await expect(page.locator('tbody')).toContainText('Custo BRL 100,00')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/positions-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Transações', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Excluir', exact: true }).click()
  await expect(page.getByText('Nenhuma transação registrada.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('Custo BRL 100,00')
  expect(updates).toBe(2)
  await page.getByRole('button', { name: 'Atualizar posições', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sua carteira começa aqui' })).toBeVisible()
  expect(updates).toBe(3)
  expect(errors).toEqual([])
})
