import { test, expect } from '@playwright/test'

test('create, price, edit and delete a position through the real API', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: '+ Carteira', exact: true }).click()
  await page.getByLabel('Nome da carteira', { exact: true }).fill('Browser test ' + Date.now())
  await page.getByRole('button', { name: 'Criar carteira', exact: true }).click()
  await page.getByRole('button', { name: '+ Nova transação', exact: true }).click()
  await page.getByLabel('Instrumento', { exact: true }).fill('WEBTEST')
  await page.getByRole('button', { name: 'Cadastrar instrumento manual', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar instrumento', exact: true }).click()
  await page.getByLabel('Corretora', { exact: true }).fill('Teste')
  await page.getByLabel('Classe de alocação', { exact: true }).fill('Ações')
  await page.getByLabel('Quantidade', { exact: true }).fill('10')
  await page.getByLabel('Preço unitário', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Salvar transação', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('WEBTEST')
  await page.getByRole('button', { name: 'Cotações', exact: true }).click()
  await page.getByLabel('Fechamento', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Salvar cotação', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('30,0000')
  await page.getByRole('button', { name: 'Posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('300,00')
  await page.screenshot({ path: 'test-results/positions-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Desempenho', exact: true }).click()
  await expect(page.getByRole('img', { name: 'Evolução histórica do ganho total' })).toBeVisible()
  await page.getByRole('button', { name: 'Transações', exact: true }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Quantidade', { exact: true }).fill('5')
  await page.getByRole('button', { name: 'Salvar transação', exact: true }).click()
  await page.getByRole('button', { name: 'Posições', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('150,00')
  const selected = await page.getByLabel('Carteira', { exact: true }).inputValue()
  await page.reload()
  await page.getByLabel('Carteira', { exact: true }).selectOption(selected)
  await expect(page.locator('tbody')).toContainText('150,00')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/positions-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Transações', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Excluir', exact: true }).click()
  await expect(page.getByText('Nenhuma transação registrada.', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
