import { test, expect } from '@playwright/test'

test('login, session restoration, space switching and logout use the real API', async ({ page }) => {
  await page.goto('/transactions')
  await expect(page.getByRole('heading', { name: 'Entre na sua conta' })).toBeVisible()
  await expect(page.getByRole('button', { name: '+ Adicionar', exact: true })).toHaveCount(0)
  const username = 'browser-auth-' + Date.now()
  await page.getByLabel('Usuário local', { exact: true }).fill(username)
  await page.getByLabel('Chave de desenvolvimento').fill('invalid')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('Chave de desenvolvimento').fill(process.env.DEV_AUTH_TOKEN ?? 'browser-test-only')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByLabel('Menu da conta')).toBeVisible()
  await expect(page.getByLabel('Espaço financeiro', { exact: true })).toHaveCount(0)
  await page.goto('/portfolios/new')
  await page.getByLabel('Nome da carteira', { exact: true }).fill('Personal portfolio')
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByRole('button', { name: 'Criar carteira', exact: true }).click()
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Personal portfolio')
  await page.goto('/settings/spaces/new')
  await page.getByLabel('Nome do novo espaço', { exact: true }).fill('Browser family')
  await page.getByRole('button', { name: 'Criar espaço', exact: true }).click()
  const selector = page.getByLabel('Espaço financeiro', { exact: true })
  await expect(selector).toContainText('Browser family')
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Nenhuma carteira')
  await expect(page.getByLabel('Carteira', { exact: true })).not.toContainText('Personal portfolio')
  const family = await selector.inputValue()
  const personal = await selector.locator('option').filter({ hasText: username }).getAttribute('value')
  await page.goto('/overview')
  await page.reload()
  await expect(selector).toHaveValue(family)
  await selector.selectOption(personal!)
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Personal portfolio')
  await page.getByLabel('Menu da conta').click()
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Entre na sua conta' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Entre na sua conta' })).toBeVisible()
})
