import { test, expect } from '@playwright/test'

test('login, session restoration, space switching and logout use the real API', async ({ page }) => {
  await page.goto('/#/transactions')
  await expect(page.getByRole('heading', { name: 'Aurion' })).toBeVisible()
  await expect(page.getByRole('button', { name: '+ Carteira', exact: true })).toHaveCount(0)
  await page.getByLabel('Usuário local', { exact: true }).fill('browser-auth-' + Date.now())
  await page.getByLabel('Chave de desenvolvimento').fill('invalid')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('Chave de desenvolvimento').fill(process.env.DEV_AUTH_TOKEN ?? 'browser-test-only')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sair', exact: true })).toBeVisible()
  const personal = await page.getByLabel('Espaço financeiro', { exact: true }).inputValue()
  await page.getByLabel('Nome da carteira', { exact: true }).fill('Personal portfolio')
  await page.getByRole('button', { name: 'Criar carteira', exact: true }).click()
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Personal portfolio')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Nome do novo espaço', { exact: true }).fill('Browser family')
  await page.getByRole('button', { name: 'Criar espaço', exact: true }).click()
  await expect(page.getByLabel('Espaço financeiro', { exact: true })).toContainText('Browser family')
  await page.getByRole('link', { name: 'Voltar para carteiras', exact: true }).click()
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Nenhuma carteira')
  await expect(page.getByLabel('Carteira', { exact: true })).not.toContainText('Personal portfolio')
  const family = await page.getByLabel('Espaço financeiro', { exact: true }).inputValue()
  await page.reload()
  await expect(page.getByLabel('Espaço financeiro', { exact: true })).toHaveValue(family)
  await page.getByLabel('Espaço financeiro', { exact: true }).selectOption(personal)
  await expect(page.getByLabel('Carteira', { exact: true })).toContainText('Personal portfolio')
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Aurion' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Aurion' })).toBeVisible()
})
