import type { FixedIncomeLot, FixedIncomeMovement } from './api'
import { Link } from './navigation'
import { dateLabel, EmptyState, fmt, MetricCard, PageHeader, StatusBadge } from './ui'
import { movementLabels } from './text'

export default function FixedIncomeDetailPage({ lot, onContribute, onRedeem, onEdit, onDelete, busy }: { busy: boolean; onDelete?: (movement: FixedIncomeMovement) => void; lot?: FixedIncomeLot; onContribute?: (id: number) => void; onRedeem?: (id: number) => void; onEdit?: (movement: FixedIncomeMovement) => void }) {
  if (!lot) return <EmptyState action={<Link href="/positions">Voltar para posições</Link>}>Aplicação não encontrada nesta carteira.</EmptyState>
  return <><PageHeader title={lot.instrument_name} description={lot.product_type + ' · ' + lot.issuer}><Link className="button outline" href="/positions">← Posições</Link>{onContribute && onRedeem && <><button className="button primary" onClick={() => onContribute(lot.id)}>Aportar</button><button className="button outline" onClick={() => onRedeem(lot.id)}>Resgatar</button></>}</PageHeader>
    <div className="detail-context"><StatusBadge status={lot.valuation?.pending ? 'pending' : lot.valuation_status} /><span>Vencimento: {dateLabel(lot.maturity_date)}</span><span>{lot.broker}</span></div>
    <div className="metrics"><MetricCard featured label={'Valor bruto · ' + (lot.valuation?.display_currency ?? lot.currency)} value={fmt(lot.valuation?.display_value)} context={'Saldo contratual · ' + lot.currency + ' ' + fmt(lot.valuation?.gross_accrued_value)} /><MetricCard label={'Principal atual · ' + (lot.valuation?.display_currency ?? lot.currency)} value={fmt(lot.valuation?.display_principal)} context={lot.currency + ' ' + fmt(lot.valuation?.outstanding_principal)} /><MetricCard label={'Rendimento em saldo · ' + (lot.valuation?.display_currency ?? lot.currency)} value={fmt(lot.valuation?.display_accrued_gain)} context={lot.currency + ' ' + fmt(lot.valuation?.accrued_gain) + ' · antes de impostos'} /></div>
    <section className="panel"><div className="section-heading"><h2>Condições da aplicação</h2><Link href="/data/benchmarks">Inspecionar benchmark →</Link></div><dl className="detail-grid">{[
      ['Principal original · ' + lot.currency, fmt(lot.valuation?.original_invested_amount ?? lot.opening_amount)], ['Data inicial', dateLabel(lot.start_date)], ['Vencimento', dateLabel(lot.maturity_date)],
      ['Modalidade', lot.yield_structure === 'FIXED_RATE' ? 'Pré-fixada' : 'Pós-fixada'], ['Indexador', lot.benchmark_code ?? 'Taxa fixa'], ['Taxa fixa a.a.', lot.fixed_rate == null ? '—' : fmt(Number(lot.fixed_rate) * 100, 4) + '%'], ['Percentual do indexador', lot.benchmark_multiplier == null ? '—' : fmt(Number(lot.benchmark_multiplier) * 100, 4) + '%'], ['Spread a.a.', lot.benchmark_spread == null ? '—' : fmt(Number(lot.benchmark_spread) * 100, 4) + '%'],
      ['Ganho realizado bruto · ' + (lot.valuation?.display_currency ?? lot.currency), fmt(lot.valuation?.display_realized_gain)], ['Base de dias', lot.day_count_basis], ['Capitalização', lot.compounding], ['Defasagem (meses)', String(lot.benchmark_lag_months)], ['Calendário', lot.business_day_calendar], ['Atualizado até', dateLabel(lot.valuation?.consolidated_through)], ['Observações', lot.notes || '—'],
    ].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value ?? '—'}</dd></div>)}</dl><p className="table-caption">Retorno percentual do lote indisponível. Valores brutos. Tributação e retorno líquido não são calculados nesta versão.</p></section>
    <section className="panel"><div className="section-heading"><h2>Linha do tempo</h2></div><ul className="activity-list">{[...lot.movements].sort((a, b) => a.effective_date.localeCompare(b.effective_date)).map(m => <li key={m.id}><strong>{movementLabels[m.movement_type]}</strong><span>{m.currency} {fmt(m.amount)}</span><small>{dateLabel(m.effective_date)} · {m.notes}</small>{onEdit && onDelete && <details className="row-menu"><summary aria-label={"Ações do movimento " + m.id}>⋯</summary><button className="button quiet" disabled={busy} onClick={() => onEdit(m)}>Editar movimento</button><button className="button danger" disabled={busy} onClick={() => onDelete(m)}>Excluir movimento</button></details>}</li>)}</ul></section>
  </>
}
