import React from 'react'
import ReactDOM from 'react-dom/client'
import AuthShell from './AuthShell'
import './styles.css'
import '@fontsource/inter/latin-400.css'
import '@fontsource/inter/latin-500.css'
import '@fontsource/inter/latin-600.css'
import '@fontsource/manrope/latin-500.css'
import '@fontsource/manrope/latin-600.css'
import '@fontsource/manrope/latin-700.css'
import './theme.css'
document.documentElement.dataset.theme = localStorage.getItem('quintrion-theme') ?? 'system'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AuthShell /></React.StrictMode>)
