import { useState } from 'react'
import type { Overview, Position, FixedIncomeLot } from './api'
import { Link } from './navigation'
import { dateLabel, EmptyState, fmt, PageHeader, StatusBadge } from './ui'

export function PositionTable({ positions }: { positions: Position[] }) {
  return <div className="table-wrap"><table aria-label="Posições de mercado"><thead><tr>{['Ativo / classe', 'Quantidade', 'Preço médio / custo', 'Cotação', 'Valor atual', 'Renda bruta', 'Resultado total', 'Status'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{positions.map(p => <tr key={p.asset_id ?? p.asset}>
    <td><Link href={'/positions/' + p.asset_id}><strong>{p.asset}</strong></Link><small>{p.allocation_class}</small></td><td>{fmt(p.quantity, 6)}</td><td>{p.display_currency} {fmt(p.display_average_cost, 4)}<small>Custo {p.display_currency} {fmt(p.display_acquisition_cost)}</small>{p.native_currency && p.native_currency !== p.display_currency && p.native_average_cost != null && <small>{p.native_currency} {fmt(p.native_average_cost, 4)} · custo {fmt(p.native_acquisition_cost)}</small>}</td>
    <td>{p.display_currency} {fmt(p.display_price)}{p.native_currency && p.native_currency === p.quote_currency && p.native_currency !== p.display_currency && <small>{p.native_currency} {fmt(p.current_price)}</small>}<small>{dateLabel(p.price_date)}{p.quote_refresh_required ? ' · atualização pendente' : ''}</small></td>
    <td>{p.display_currency} {fmt(p.display_value)}{p.native_currency && p.native_currency === p.quote_currency && p.native_currency !== p.display_currency && <small>{p.native_currency} {fmt(p.total_value)}</small>}</td><td>{p.display_currency} {fmt(p.gross_income)}{p.native_currency && p.native_currency !== p.display_currency && <small>{p.native_currency} {fmt(p.native_gross_income)}</small>}</td>
    <td className={Number(p.current_total_gain ?? 0) >= 0 ? 'positive' : 'negative'}>{p.display_currency} {fmt(p.current_total_gain)}<small>{p.current_accumulated_profitability == null ? 'Retorno histórico indisponível' : fmt(p.current_accumulated_profitability) + '%' + (p.return_date ? ' até ' + dateLabel(p.return_date) : '')}</small></td><td><StatusBadge status={p.status} />{p.history_behind_transactions && <small>Cotação anterior à última atividade</small>}</td>
  </tr>)}</tbody></table>{!positions.length && <EmptyState>Nenhuma posição corresponde aos filtros.</EmptyState>}</div>
}
export function LotTable({ lots, onContribute, onRedeem }: { lots: FixedIncomeLot[]; onContribute?: (id: number) => void; onRedeem?: (id: number) => void }) {
  return <div className="table-wrap"><table aria-label="Lotes de renda fixa"><thead><tr>{['Instrumento', 'Emissor / corretora', 'Rendimento', 'Aplicação / vencimento', 'Valor aplicado', 'Saldo atual', 'Resultado bruto', 'Status', 'Ações'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{lots.map(lot => <tr key={lot.id}>
    <td><Link href={'/fixed-income/' + lot.id}><strong>{lot.instrument_symbol}</strong></Link><small>{lot.instrument_name}</small></td><td>{lot.issuer}<small>{lot.broker}</small></td><td>{lot.yield_structure === 'FIXED_RATE' ? `${fmt(Number(lot.fixed_rate) * 100)}% a.a.` : lot.yield_structure === 'BENCHMARK_MULTIPLE' ? `${fmt(Number(lot.benchmark_multiplier) * 100)}% do ${lot.benchmark_code}` : `${lot.benchmark_code} + ${fmt(Number(lot.benchmark_spread) * 100)}% a.a.`}</td><td>{dateLabel(lot.start_date)}<small>Vencimento {dateLabel(lot.maturity_date)}</small></td>
    <td>{lot.currency} {fmt(lot.opening_amount)}</td><td>{lot.valuation?.display_currency ?? lot.currency} {fmt(lot.valuation?.display_value)}<small>Principal {lot.currency} {fmt(lot.valuation?.outstanding_principal)}</small>{lot.valuation?.display_currency !== lot.currency && <small>Bruto {lot.currency} {fmt(lot.valuation?.gross_accrued_value)}</small>}{lot.valuation?.pending && <small>Atualização pendente · use Atualizar carteira</small>}</td><td>{lot.currency} {fmt(lot.valuation?.accrued_gain)}<small>Antes de impostos</small></td><td><StatusBadge status={lot.valuation?.pending ? 'pending' : lot.valuation_status} /></td><td>{onContribute && onRedeem && <details className="row-menu"><summary aria-label={'Ações de ' + lot.instrument_symbol}>⋯</summary><button className="button quiet" onClick={() => onContribute(lot.id)}>Aportar</button><button className="button quiet" onClick={() => onRedeem(lot.id)}>Resgatar</button></details>}</td>
  </tr>)}</tbody></table>{!lots.length && <EmptyState>Nenhum lote corresponde aos filtros.</EmptyState>}</div>
}
export default function PositionsPage({ overview, lots, onContribute, onRedeem, onAdd }: { overview: Overview; lots: FixedIncomeLot[]; onContribute?: (id: number) => void; onRedeem?: (id: number) => void; onAdd?: () => void }) {
  const [query, setQuery] = useState(''), [assetClass, setClass] = useState(''), [currency, setCurrency] = useState(''), [broker, setBroker] = useState(''), [showClosed, setShowClosed] = useState(false), [status, setStatus] = useState(''), [type, setType] = useState(new URLSearchParams(window.location.search).get('type') ?? '')
  const market = overview.positions.filter(p => p.position_type !== 'FIXED_INCOME')
  const filtered = market.filter(p => (showClosed || p.quantity == null || Number(p.quantity) !== 0) && (!status || status === 'closed' ? !status || p.quantity != null && Number(p.quantity) === 0 : p.quantity == null || Number(p.quantity) !== 0) && [p.asset, p.allocation_class].join(' ').toLowerCase().includes(query.toLowerCase()) && (!assetClass || p.allocation_class === assetClass) && (!currency || (p.native_currency ?? p.transaction_currency) === currency) && (!broker || p.broker === broker || p.broker_breakdown?.some(b => b.broker === broker)))
  const filteredLots = lots.filter(lot => (showClosed || lot.valuation?.gross_accrued_value == null || Number(lot.valuation.gross_accrued_value) !== 0) && (!status || status === 'closed' ? !status || Number(lot.valuation?.gross_accrued_value) === 0 : lot.valuation?.gross_accrued_value == null || Number(lot.valuation.gross_accrued_value) !== 0) && [lot.instrument_symbol, lot.instrument_name, lot.issuer, lot.broker, 'Renda fixa'].join(' ').toLowerCase().includes(query.toLowerCase()) && (!currency || lot.currency === currency) && (!broker || lot.broker === broker) && (!assetClass || assetClass === 'Renda fixa'))
  return <><PageHeader title="Posições" description="Ativos de mercado por instrumento e renda fixa por aplicação." />
    <section className="panel"><div className="filter-bar"><label>Buscar posições<input placeholder="Buscar ativo ou classe…" value={query} onChange={e => setQuery(e.target.value)} /></label>{([
      ['Classe', assetClass, setClass, [...new Set([...market.map(p => p.allocation_class), ...(lots.length ? ['Renda fixa'] : [])])]],
      ['Moeda', currency, setCurrency, [...new Set([...market.map(p => p.native_currency ?? p.transaction_currency ?? ''), ...lots.map(l => l.currency)])]],
      ['Corretora', broker, setBroker, [...new Set([...market.flatMap(p => p.broker_breakdown?.map(b => b.broker) ?? [p.broker]), ...lots.map(l => l.broker)])]],
    ] as const).map(([label, value, setter, options]) => <label key={label}>{label}<select value={value} onChange={e => setter(e.target.value)}><option value="">Todas</option>{options.filter(Boolean).map(option => <option key={option}>{option}</option>)}</select></label>)}
    <label>Tipo de posição<select value={type} onChange={e => setType(e.target.value)}><option value="">Todos</option><option value="market">Mercado</option><option value="fixed">Renda fixa</option></select></label><label>Status da posição<select value={status} onChange={e => { setStatus(e.target.value); if (e.target.value === 'closed') setShowClosed(true) }}><option value="">Todos</option><option value="active">Ativas</option><option value="closed">Encerradas</option></select></label></div>
    <label className="checkbox-control"><input type="checkbox" checked={showClosed} onChange={e => setShowClosed(e.target.checked)} />Mostrar posições encerradas</label></section>
    {!market.length && !lots.length && <EmptyState action={onAdd && <button className="button primary" onClick={onAdd}>Adicionar primeira transação</button>}>Nenhuma posição registrada. Adicione ou importe suas operações.</EmptyState>}
    {type !== 'fixed' && <section className="panel"><div className="section-heading"><h2>Composição da carteira</h2><span>{overview.summary.display_currency}</span></div><PositionTable positions={filtered} /></section>}
    {type !== 'market' && lots.length > 0 && <section className="panel"><div className="section-heading"><h2>Renda fixa</h2><p>Valor bruto contratual por lote, antes de impostos.</p></div><LotTable lots={filteredLots} onContribute={onContribute} onRedeem={onRedeem} /></section>}
  </>
}
