import { useState } from 'react'
import { api, type Transaction, type FixedIncomeLot, type FixedIncomeMovement } from './api'
import { Link } from './navigation'
import { movementLabels } from './text'
import { dateLabel, EmptyState, fmt, PageHeader, type Mutate } from './ui'

export function TransactionTable({ transactions, busy, onEdit, onDelete }: { transactions: Transaction[]; busy?: boolean; onEdit?: (tx: Transaction) => void; onDelete?: (tx: Transaction) => void }) {
  return <div className="table-wrap"><table aria-label="Transações de mercado"><thead><tr>{['Negociação / liquidação', 'Operação', 'Ativo / moeda', 'Corretora / classe', 'Quantidade', 'Preço / FX', 'Taxas', 'Ações'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{transactions.map(tx => <tr key={tx.id}>
    <td><Link href={'/transactions/' + tx.id}>{dateLabel(tx.trade_date)}</Link><small>{dateLabel(tx.settlement_date)}</small></td><td><span className={'badge ' + (tx.type === 'Buy' ? 'buy' : 'sell')}>{tx.type === 'Buy' ? 'Compra' : 'Venda'}</span></td><td><Link href={'/transactions/' + tx.id}><strong>{tx.asset}</strong></Link><small>{tx.transaction_currency} · {tx.notes}</small></td><td>{tx.broker}<small>{tx.allocation_class}</small></td><td>{fmt(tx.quantity, 6)}</td><td>{fmt(tx.price, 4)}<small>FX {fmt(tx.fx_rate, 6)}</small></td><td>{fmt(Number(tx.brokerage_fee) + Number(tx.other_fees))}</td><td>{onEdit && onDelete && <details className="row-menu"><summary aria-label={'Ações da transação ' + tx.id}>⋯</summary><button className="button quiet" disabled={busy} onClick={() => onEdit(tx)}>Editar</button><button className="button danger" disabled={busy} onClick={() => onDelete(tx)}>Excluir</button></details>}</td>
  </tr>)}</tbody></table>{!transactions.length && <EmptyState>Nenhuma transação de mercado corresponde aos filtros.</EmptyState>}</div>
}
export default function TransactionsPage({ portfolioId, transactions, lots, busy, readOnly, mutate, onEdit, onEditMovement, onAdd }: { portfolioId: number; transactions: Transaction[]; lots: FixedIncomeLot[]; busy: boolean; readOnly: boolean; mutate: Mutate; onEdit: (tx: Transaction) => void; onEditMovement: (movement: FixedIncomeMovement) => void; onAdd: () => void }) {
  const [query, setQuery] = useState(''), [type, setType] = useState(''), [currency, setCurrency] = useState(''), [broker, setBroker] = useState(''), [assetClass, setAssetClass] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState('')
  const inRange = (day: string) => (!start || day >= start) && (!end || day <= end)
  const txs = transactions.filter(t => (!type || t.type === type) && (!currency || t.transaction_currency === currency) && (!broker || t.broker === broker) && (!assetClass || t.allocation_class === assetClass) && inRange(t.trade_date) && t.asset.toLowerCase().includes(query.toLowerCase()))
  const movements = lots.flatMap(lot => lot.movements.map(movement => ({ lot, movement }))).filter(({ lot, movement }) => (!type || movement.movement_type === type) && (!currency || lot.currency === currency) && (!broker || lot.broker === broker) && (!assetClass || assetClass === 'Renda fixa') && inRange(movement.effective_date) && lot.instrument_symbol.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.movement.effective_date.localeCompare(a.movement.effective_date))
  function remove(tx: Transaction) { if (window.confirm('Excluir esta transação? A atualização das posições ficará pendente.')) void mutate(() => api('/portfolios/' + portfolioId + '/transactions/' + tx.id, 'DELETE'), 'Transação excluída. Atualização das posições pendente.') }
  return <><PageHeader title="Transações" description="Compras, vendas, aplicações, aportes e resgates da carteira.">{!readOnly && <><button className="button primary" onClick={onAdd}>+ Nova transação</button><Link className="button outline" href="/transactions/import">Importar transações</Link></>}</PageHeader>
    <section className="panel filter-bar"><label>Instrumento<input value={query} onChange={e => setQuery(e.target.value)} /></label><label>De<input type="date" value={start} max={end || undefined} onChange={e => setStart(e.target.value)} /></label><label>Até<input type="date" value={end} min={start || undefined} onChange={e => setEnd(e.target.value)} /></label><label>Tipo de transação<select value={type} onChange={e => setType(e.target.value)}><option value="">Todos</option><option value="Buy">Compra</option><option value="Sell">Venda</option>{Object.entries(movementLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
    {([['Moeda', currency, setCurrency, [...new Set([...transactions.map(t => t.transaction_currency), ...lots.map(l => l.currency)])]], ['Corretora', broker, setBroker, [...new Set([...transactions.map(t => t.broker), ...lots.map(l => l.broker)])]], ['Classe', assetClass, setAssetClass, [...new Set([...transactions.map(t => t.allocation_class), ...(lots.length ? ['Renda fixa'] : [])])]]] as const).map(([label, value, setter, options]) => <label key={label}>{label}<select value={value} onChange={e => setter(e.target.value)}><option value="">Todas</option>{options.map(option => <option key={option}>{option}</option>)}</select></label>)}</section>
    <p className="method-note">A origem manual/importação não é exposta por operação nesta versão. Eventos corporativos estão em Dados de mercado.</p>
    <section className="panel"><div className="section-heading"><h2>Histórico de operações</h2><p>Editar, excluir ou importar deixa a atualização das posições pendente.</p></div><TransactionTable transactions={txs} busy={busy} onEdit={readOnly ? undefined : onEdit} onDelete={readOnly ? undefined : remove} /></section>
    {!!lots.length && <section className="panel"><div className="section-heading"><h2>Movimentos de renda fixa</h2><p>Valores contratuais na moeda de cada lote.</p></div><div className="table-wrap"><table aria-label="Movimentos de renda fixa"><thead><tr><th>Data</th><th>Instrumento / emissor</th><th>Movimento</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{movements.map(({ lot, movement: m }) => <tr key={m.id}><td>{dateLabel(m.effective_date)}</td><td><Link href={'/fixed-income/' + lot.id}>{lot.instrument_symbol}</Link><small>{lot.issuer}</small></td><td>{movementLabels[m.movement_type]}</td><td>{m.currency} {fmt(m.amount)}</td><td>{!readOnly && <details className="row-menu"><summary aria-label={'Ações do movimento ' + m.id}>⋯</summary><button className="button quiet" disabled={busy} onClick={() => onEditMovement(m)}>Editar</button><button className="button danger" disabled={busy} onClick={() => {
      if (window.confirm(m.movement_type === 'INITIAL_INVESTMENT' ? 'Excluir a aplicação inicial e o lote? Movimentos futuros podem impedir a exclusão; a atualização das posições ficará pendente.' : 'Excluir este movimento? Movimentos posteriores podem impedir a exclusão; a atualização ficará pendente.')) void mutate(() => api(`/portfolios/${portfolioId}/fixed-income/lots/${lot.id}/movements/${m.id}`, 'DELETE'), 'Movimento excluído. Atualização das posições pendente.')
    }}>Excluir</button></details>}</td></tr>)}</tbody></table>{!movements.length && <EmptyState>Nenhum movimento corresponde aos filtros.</EmptyState>}</div></section>}
  </>
}
